Karthikvijayan/samplebuilder
salesforce/bazel-java-builder-template pull request #1
Opened 2019-09-23 17:33 UTC by karthikvijayan

2019-09-23 17:34 UTC, karthikvijayan commented on mybuilder/mybuilder.bzl
> +        #jar_sha256 = "9bc4992d3b7d98885a2c42c301654f54b13a5747",
I'll try and compute this after downloading the jar, if not ill defer to bazel to do it.

2019-09-24 14:30 UTC, guw requested changes

2019-09-24 14:30 UTC, guw commented on src/main/java/com/salesforce/bazel/javabuilder/mybuilder/MyBuilderProcessor.java
> +    	BufferedWriter writer = new BufferedWriter(new FileWriter(outputFile));
This should be try-with-resources. Use static import from `Files` class.

2019-09-24 14:30 UTC, guw commented on src/main/java/com/salesforce/bazel/javabuilder/mybuilder/MyBuilderProcessor.java
> +        BufferedReader br = new BufferedReader(new FileReader(file));
Use try-with-resources. Have a look at static utility methods in JDK `Files` class.

2019-09-24 16:11 UTC, guw approved these changes

2019-09-24 16:11 UTC, merged